# -*- coding: utf-8 -*-
"""Untitled82.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O0Ko4YAiuP9-yXTGGxg8gB7ZrLOYJCCC
"""

import requests, json


api_key = "bda584c1162c74a779e601e263892af6"


base_url = "http://api.openweathermap.org/data/2.5/weather?"


city_name = input("Enter city name : ")


complete_url = base_url + "appid=" + api_key + "&q=" + city_name


response = requests.get(complete_url)


x = response.json()


if x["cod"] != "404":

	
	y = x["main"]


	current_temperature = y["temp"]

	
	current_pressure = y["pressure"]

	
	current_humidity = y["humidity"]


	z = x["weather"]

	
	weather_description = z[0]["description"]


	print(" Temperature (in kelvin unit) = " +
					str(current_temperature) +
		"\n atmospheric pressure (in hPa unit) = " +
					str(current_pressure) +
		"\n humidity (in percentage) = " +
					str(current_humidity) +
		"\n description = " +
					str(weather_description))

else:
	print(" City Not Found ")